### ISSUE TITLE
Add a quick sort algorithm

### ISSUE THREAD

**Issue by DanielRomeo** [DanielRomeo/sortingAlgorithms#1]
# Description 
This project is in **vanilla JS** and **p5.js**. This is a p5.js project, that visualizes sorting algorithms.

```bash
Add a Quick Sort function algorithm at the end of the Sketch.Js file. 
```
## Steps
1. Fork the repository
1. Clone the repository you have forked (Appears in the repository section of your profile)
3. Checkout to a new branch. (Optional if you don't have a concept of branching)
4. Write the function in the Sketch.js file. Don't worry about linking it to the main index.html page, you may if you're able to.
5. Commit the changes
6. Create a PR to the original repository

**Comment by SravanthiKaki** [comment]
Can You assign this to me?

**Comment by DanielRomeo** [comment]
> Can You assign this to me?

go ahead.

**Comment by DanielRomeo** [comment]
Hey @SravanthiKaki , u still wanna do this? or should i close it

**Comment by DanielRomeo** [comment]
You took too long to do this
